// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"DemoLayout":{"id":"DemoLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"components/sl_icon/index":{"id":"components/sl_icon/index","path":"components/sl_icon","parentId":"DocLayout","meta":{"_atom_route":true}},"components/sl_upload_oss/index":{"id":"components/sl_upload_oss/index","path":"components/sl_upload_oss","parentId":"DocLayout","meta":{"_atom_route":true}},"oms/oms/index":{"id":"oms/oms/index","path":"oms/oms","parentId":"DocLayout","meta":{"_atom_route":true}},"oms/permissions/index":{"id":"oms/permissions/index","path":"oms/permissions","parentId":"DocLayout","meta":{"_atom_route":true}},"oms/public/index":{"id":"oms/public/index","path":"oms/public","parentId":"DocLayout","meta":{"_atom_route":true}},"oms/sy_web/index":{"id":"oms/sy_web/index","path":"oms/sy_web","parentId":"DocLayout","meta":{"_atom_route":true}},"oms/sy/index":{"id":"oms/sy/index","path":"oms/sy","parentId":"DocLayout","meta":{"_atom_route":true}},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"DemoLayout"}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/liuxiang/Desktop/简爱项目/lx-document/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'/Users/liuxiang/Desktop/简爱项目/lx-document/.dumi/tmp/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'/Users/liuxiang/Desktop/简爱项目/lx-document/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'DemoLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi-theme-mobile__dist__layouts__DemoLayout" */'/Users/liuxiang/Desktop/简爱项目/lx-document/node_modules/dumi-theme-mobile/dist/layouts/DemoLayout.js')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'/Users/liuxiang/Desktop/简爱项目/lx-document/docs/index.md')),
'components/sl_icon/index': React.lazy(() => import(/* webpackChunkName: "components__sl_icon__index.md" */'/Users/liuxiang/Desktop/简爱项目/lx-document/src/components/sl_icon/index.md')),
'components/sl_upload_oss/index': React.lazy(() => import(/* webpackChunkName: "components__sl_upload_oss__index.md" */'/Users/liuxiang/Desktop/简爱项目/lx-document/src/components/sl_upload_oss/index.md')),
'oms/oms/index': React.lazy(() => import(/* webpackChunkName: "sdks__oms__index.md" */'/Users/liuxiang/Desktop/简爱项目/lx-document/src/sdks/oms/index.md')),
'oms/permissions/index': React.lazy(() => import(/* webpackChunkName: "sdks__permissions__index.md" */'/Users/liuxiang/Desktop/简爱项目/lx-document/src/sdks/permissions/index.md')),
'oms/public/index': React.lazy(() => import(/* webpackChunkName: "sdks__public__index.md" */'/Users/liuxiang/Desktop/简爱项目/lx-document/src/sdks/public/index.md')),
'oms/sy_web/index': React.lazy(() => import(/* webpackChunkName: "sdks__sy_web__index.md" */'/Users/liuxiang/Desktop/简爱项目/lx-document/src/sdks/sy_web/index.md')),
'oms/sy/index': React.lazy(() => import(/* webpackChunkName: "sdks__sy__index.md" */'/Users/liuxiang/Desktop/简爱项目/lx-document/src/sdks/sy/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/liuxiang/Desktop/简爱项目/lx-document/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
