// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export * from '../exports';
export * from '/Users/liuxiang/Desktop/简爱项目/lx-document/node_modules/dumi/dist/client/theme-api/index.js';
