// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/liuxiang/Desktop/简爱项目/lx-document/node_modules/dumi/theme-default/slots/SocialIcon/index.js';
